name: textured-smplx
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch=*=*cuda11.8*
  - pytorch-cuda=11.8
  - pytorch3d=*=*cu118*
  - pip<24.1
  - pip:
      - -r ./requirements.txt